// <auto-generated />
using System;
using System.Collections.Generic;
using Interação_Medicamentosa.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Interação_Medicamentosa.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Interação_Medicamentosa.Models.InteraçãoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrição")
                        .HasColumnType("text");

                    b.Property<int>("MedicamentoId_1")
                        .HasColumnType("integer");

                    b.Property<int>("MedicamentoId_2")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Risco")
                        .HasColumnType("text");

                    b.Property<string>("Substancia")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MedicamentoId_1");

                    b.HasIndex("MedicamentoId_2");

                    b.ToTable("Interações");
                });

            modelBuilder.Entity("Interação_Medicamentosa.Models.MedicamentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Armazenamento")
                        .HasColumnType("text");

                    b.Property<string>("ClasseTerapeutica")
                        .HasColumnType("text");

                    b.Property<string>("Fabricante")
                        .HasColumnType("text");

                    b.Property<string>("FormaFarmaceutica")
                        .HasColumnType("text");

                    b.Property<string>("Indicacoes")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoMax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecoMin")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("Interação_Medicamentosa.Models.PacienteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("CondicoesMedicas")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<DateTime>("UltimaVisita")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Interação_Medicamentosa.Models.PrescriçãoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Dosagem")
                        .HasColumnType("integer");

                    b.Property<int>("Duracao")
                        .HasColumnType("integer");

                    b.Property<int>("HorariodoRemedio")
                        .HasColumnType("integer");

                    b.Property<int>("IdMedicamento")
                        .HasColumnType("integer");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("frequencia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdMedicamento");

                    b.HasIndex("IdPaciente");

                    b.ToTable("Prescrições");
                });

            modelBuilder.Entity("Interação_Medicamentosa.Models.InteraçãoModel", b =>
                {
                    b.HasOne("Interação_Medicamentosa.Models.MedicamentoModel", "Medicamento_1")
                        .WithMany()
                        .HasForeignKey("MedicamentoId_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interação_Medicamentosa.Models.MedicamentoModel", "Medicamento_2")
                        .WithMany()
                        .HasForeignKey("MedicamentoId_2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento_1");

                    b.Navigation("Medicamento_2");
                });

            modelBuilder.Entity("Interação_Medicamentosa.Models.PrescriçãoModel", b =>
                {
                    b.HasOne("Interação_Medicamentosa.Models.MedicamentoModel", "Medicamento")
                        .WithMany()
                        .HasForeignKey("IdMedicamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interação_Medicamentosa.Models.PacienteModel", null)
                        .WithMany("Prescrições")
                        .HasForeignKey("IdPaciente");

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("Interação_Medicamentosa.Models.PacienteModel", b =>
                {
                    b.Navigation("Prescrições");
                });
#pragma warning restore 612, 618
        }
    }
}
